apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-hunter
spec:
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kube-hunter
            image: aquasec/kube-hunter
            imagePullPolicy: IfNotPresent
            command: ["kube-hunter"]
            args: ["--pod"]
          restartPolicy: Never
      backoffLimit: 4
