apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-update
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: coredns-update
rules:
- apiGroups: ["", "apps", "rbac.authorization.k8s.io", "discovery.k8s.io", "policy", "extensions"] # "" indicates the core API group
  resources: ["nodes", "replicationcontrollers/scale", "deployments/scale", "replicasets/scale", "poddisruptionbudgets", "serviceaccounts", "clusterroles", "clusterrolebindings", "deployments", "configmaps", "endpoints", "namespaces", "pods", "services", "endpointslices"]
  verbs: ["get", "patch", "create", "list", "watch", "update"]
- apiGroups: ["", "apps"]
  resources: ["services", "deployments"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: coredns-update
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: coredns-update
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: coredns-update
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-update-script
data:
  script.sh: |
    #!/usr/bin/env bash

    set -euo pipefail
    
    COREDNS_IP=$(dig +short coredns.github.io | head -n 1)
    KUBE_IP=$(dig +short kubernetes.default | head -n 1)
    HELM_REPO_IP=$(dig +short charts.helm.sh | head -n 1)
    GITHUB_IP=$(dig +short github.com | head -n 1)
    GITHUB_USER_IP=$(dig +short github-releases.githubusercontent.com | head -n 1)
    echo "$COREDNS_IP coredns.github.io" >> /etc/hosts
    echo "$KUBE_IP kubernetes.default" >> /etc/hosts
    echo "$HELM_REPO_IP charts.helm.sh" >> /etc/hosts
    echo "$GITHUB_IP github.com" >> /etc/hosts
    echo "$GITHUB_USER_IP github-releases.githubusercontent.com" >> /etc/hosts
    cat /etc/hosts

    curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default/

    HELM=$(which helm)
    KUBECTL=$(which kubectl) 

    if [[ $(helm ls -A | grep "coredns" | awk '{print $1}') == "coredns" ]] 
    then
        echo "Chart is already installed"
        exit 0
    else
        for resource in deployment serviceAccount configMap; do 
            echo "Setting annotations and labels on $resource/coredns" 
            kubectl -n kube-system annotate --overwrite $resource coredns meta.helm.sh/release-name=coredns 
            kubectl -n kube-system annotate --overwrite $resource coredns meta.helm.sh/release-namespace=kube-system 
            kubectl -n kube-system label --overwrite $resource coredns app.kubernetes.io/managed-by=Helm 
        done 

        # Get the clusterIP for the Helm install 
        CLUSTER_IP=$(kubectl get svc -n kube-system kube-dns -o jsonpath='{.spec.clusterIP}')
        # Remove the service because patching it is a pain. 
        $KUBECTL -n kube-system delete service kube-dns
        $KUBECTL -n kube-system delete deployment coredns
        # Service resources can take a few seconds to delete, deletion has exceeded 5s on occasion. 
        # If the service has not deleted in time, the chart installation will fail.
        sleep 10
        # Install a chart that fleet will take ownership of 
        $HELM repo add coredns https://coredns.github.io/helm 
        $HELM upgrade --install coredns -n kube-system coredns/coredns --set service.clusterIP="${CLUSTER_IP}" --set fullnameOverride="coredns" --force
    fi 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: coredns-update
spec:
  template:
    spec:
      serviceAccount: coredns-update
      serviceAccountName: coredns-update
      volumes:
      - name: coredns-update-script
        configMap:
          name: coredns-update-script
          defaultMode: 0777
      containers:
      - name: coredns-update
        image: dtzar/helm-kubectl:3.6.2
        volumeMounts:
          - mountPath: /coredns-update-script
            name: coredns-update-script
        command:
        - /bin/sh
        - -c
        - |
          /coredns-update-script/script.sh
      restartPolicy: Never
  backoffLimit: 0
